version: '3.8'
services:
  web:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:3000"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=production
